

package com.javiersc.kotlin.kopy.compiler;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.test.util.KtTestUtil;
import org.jetbrains.kotlin.test.TargetBackend;
import org.jetbrains.kotlin.test.TestMetadata;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.util.regex.Pattern;

/** This class is generated by {@link com.javiersc.kotlin.kopy.compiler.GenerateKotlinCompilerTestsKt}. DO NOT MODIFY MANUALLY */
@SuppressWarnings("all")
@TestMetadata("test-data/diagnostics-kopy-functions/all")
@TestDataPath("$PROJECT_ROOT")
public class KopyAllDiagnosticTestGenerated extends AbstractKopyAllDiagnosticTest {
  @Test
  @TestMetadata("all.kt")
  public void testAll() {
    runTest("test-data/diagnostics-kopy-functions/all/all.kt");
  }

  @Test
  public void testAllFilesPresentInAll() {
    KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("test-data/diagnostics-kopy-functions/all"), Pattern.compile("^(.+)\\.kt$"), null, TargetBackend.JVM_IR, true);
  }
}
