

package com.javiersc.kotlin.kopy.compiler;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.test.util.KtTestUtil;
import org.jetbrains.kotlin.test.TargetBackend;
import org.jetbrains.kotlin.test.TestMetadata;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.util.regex.Pattern;

/** This class is generated by {@link com.javiersc.kotlin.kopy.compiler.GenerateKotlinCompilerTestsKt}. DO NOT MODIFY MANUALLY */
@SuppressWarnings("all")
@TestMetadata("test-data/diagnostics-kopy-visibility/0_auto")
@TestDataPath("$PROJECT_ROOT")
public class Kopy0AutoDiagnosticTestGenerated extends AbstractKopy0AutoDiagnosticTest {
  @Test
  public void testAllFilesPresentIn0_auto() {
    KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("test-data/diagnostics-kopy-visibility/0_auto"), Pattern.compile("^(.+)\\.kt$"), null, TargetBackend.JVM_IR, true);
  }

  @Test
  @TestMetadata("internal.kt")
  public void testInternal() {
    runTest("test-data/diagnostics-kopy-visibility/0_auto/internal.kt");
  }

  @Test
  @TestMetadata("private.kt")
  public void testPrivate() {
    runTest("test-data/diagnostics-kopy-visibility/0_auto/private.kt");
  }

  @Test
  @TestMetadata("private_2.kt")
  public void testPrivate_2() {
    runTest("test-data/diagnostics-kopy-visibility/0_auto/private_2.kt");
  }

  @Test
  @TestMetadata("protected.kt")
  public void testProtected() {
    runTest("test-data/diagnostics-kopy-visibility/0_auto/protected.kt");
  }

  @Test
  @TestMetadata("public.kt")
  public void testPublic() {
    runTest("test-data/diagnostics-kopy-visibility/0_auto/public.kt");
  }
}
