

package com.javiersc.kotlin.kopy.compiler;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.test.util.KtTestUtil;
import org.jetbrains.kotlin.test.TestMetadata;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.util.regex.Pattern;

/** This class is generated by {@link com.javiersc.kotlin.kopy.compiler.GenerateKotlinCompilerTestsKt}. DO NOT MODIFY MANUALLY */
@SuppressWarnings("all")
@TestMetadata("test-data/diagnostics-kopy-visibility/4_private")
@TestDataPath("$PROJECT_ROOT")
public class Kopy4PrivateDiagnosticTestGenerated extends AbstractKopy4PrivateDiagnosticTest {
  @Test
  public void testAllFilesPresentIn4_private() {
    KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("test-data/diagnostics-kopy-visibility/4_private"), Pattern.compile("^(.+)\\.kt$"), null, true);
  }

  @Test
  @TestMetadata("internal.kt")
  public void testInternal() {
    runTest("test-data/diagnostics-kopy-visibility/4_private/internal.kt");
  }

  @Test
  @TestMetadata("private.kt")
  public void testPrivate() {
    runTest("test-data/diagnostics-kopy-visibility/4_private/private.kt");
  }

  @Test
  @TestMetadata("protected.kt")
  public void testProtected() {
    runTest("test-data/diagnostics-kopy-visibility/4_private/protected.kt");
  }

  @Test
  @TestMetadata("public.kt")
  public void testPublic() {
    runTest("test-data/diagnostics-kopy-visibility/4_private/public.kt");
  }
}
