name: apply-format

on:
  workflow_dispatch:

jobs:
  apply-format:
    uses: JavierSegoviaCordoba/reusable-workflows/.github/workflows/apply-format.yaml@28cbbb75290c493db804578d91b71776b7eaf8f7 # main
    secrets: inherit
