name: apply-format

on:
  workflow_dispatch:

jobs:
  apply-format:
    uses: JavierSegoviaCordoba/reusable-workflows/.github/workflows/apply-format.yaml@8d924922af2a2897f5d8bf57e29cdef23a93d64c # main
    secrets: inherit
