name: build-kotlin

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'

  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.md'

jobs:
  build:
    uses: JavierSegoviaCordoba/reusable-workflows/.github/workflows/build-kotlin.yaml@8d924922af2a2897f5d8bf57e29cdef23a93d64c # main
    with:
      allow-github-actor-bots: false
      deploy-docs: false
      publish-snapshot: true
      run_before_args: './gradlew assemble publishToMavenLocalTest'
    secrets: inherit
