name: fix-checks

on:
  workflow_dispatch:

jobs:
  fix-checks:
    uses: JavierSegoviaCordoba/reusable-workflows/.github/workflows/fix-checks.yaml@b3f4c6f534709f4429658f3e1441243032e48b14 # main
    secrets: inherit
