name: fix-checks

on:
  workflow_dispatch:

jobs:
  fix-checks:
    uses: JavierSegoviaCordoba/reusable-workflows/.github/workflows/fix-checks.yaml@28cbbb75290c493db804578d91b71776b7eaf8f7 # main
    secrets: inherit
