name: fix-checks

on:
  workflow_dispatch:

jobs:
  fix-checks:
    uses: JavierSegoviaCordoba/reusable-workflows/.github/workflows/fix-checks.yaml@4fed19bced81f4d1690fab4679e6453c774b0909 # main
    secrets: inherit
