name: generate-version-tag

on:
  workflow_dispatch:
    if: github.ref == 'refs/heads/main'
    inputs:
      stage:
        description: 'Stage'
        required: true
        default: 'auto'
        type: choice
        options:
          - 'alpha'
          - 'beta'
          - 'rc'
          - 'final'
          - 'auto'
      scope:
        description: 'Scope'
        required: true
        default: 'auto'
        type: choice
        options:
          - 'patch'
          - 'minor'
          - 'major'
          - 'auto'

jobs:
  generate:
    uses: JavierSegoviaCordoba/reusable-workflows/.github/workflows/generate-version-tag.yaml@b3f4c6f534709f4429658f3e1441243032e48b14 # main
    with:
      stage: '${{ github.event.inputs.stage }}'
      scope: '${{ github.event.inputs.scope }}'
    secrets: inherit
