name: publish-kotlin

on:
  push:
    tags:
      - '**'

jobs:
  publish:
    uses: JavierSegoviaCordoba/reusable-workflows/.github/workflows/publish-kotlin.yaml@28cbbb75290c493db804578d91b71776b7eaf8f7 # main
    with:
      publish-maven-central: true
      publish-gradle-plugin-portal: true
      #TODO: publish-jetbrains-marketplace: "{{ publish-jetbrains-marketplace }}"
      publish-docs: true
      publish-github-release: true
      run_before_args: './gradlew assemble publishToMavenLocalTest'
    secrets: inherit
