name: publish-kotlin

on:
  push:
    tags:
      - '**'

jobs:
  publish:
    uses: JavierSegoviaCordoba/reusable-workflows/.github/workflows/publish-kotlin.yaml@8d924922af2a2897f5d8bf57e29cdef23a93d64c # main
    with:
      publish-maven-central: true
      publish-gradle-plugin-portal: true
      #TODO: publish-jetbrains-marketplace: "{{ publish-jetbrains-marketplace }}"
      publish-docs: true
      publish-github-release: true
      run_before_args: './gradlew assemble publishToMavenLocalTest'
    secrets: inherit
